### ISSUE TITLE
ranking page css v1.0

### ISSUE THREAD

**Issue by jhn25** [kjs990114/SKKU.GG#15]
# Ranking Page CSS V1.0

![image](https://user-images.githubusercontent.com/115395599/204257854-64452191-c239-4c3f-b156-c682f423c70e.png)

## 고려 사항
- tier를 이미지로 가져오고, 티어별로 색을 다르게 했을때의 가독성 문제
- depart 별로 랭킹을 다르게 표현하는 것(전체, software, ..._)
- Tier와 랭크 파트를 합쳐서 표기(unrank, 마스터 이후 모두 티어가 1 인점을 감안)

**Comment by kjs990114** [comment]
티어 이미지넣기와
[학과별 sorting기능](#2 )이 필요한것 같습니다.

**Comment by jhn25** [comment]
<img width="1440" alt="스크린샷 2022-11-29 오전 4 43 55" src="https://user-images.githubusercontent.com/115395599/204367165-1f524337-448a-40d8-b92c-2221fb6b986e.png">

## 반영사항
- 티어이미지 구현
- css 변경

## 수정필요한 사항
- 티어별 sorting
